### ISSUE TITLE
hi,请问一下，这个在appium2.0以上的版本还生效吗

### ISSUE THREAD

**Issue by lyfengcc** [aaroncarry/appium-mocker#1]

**Comment by aaroncarry** [comment]
Appium mocker 这个工具只是mock出一个与Appium server交互的client，具体client的表现其实是依赖于Appium mocker中引用的appium-java-client的版本. 目前appium mocker中基于的appium-java-client版本是7.3.0。

据我了解，appium2.0 对capabilities prefix做了一些更严格的约束，原有的appium client不一定能直接支持2.0的appium，你可以在appium2.0上试着引用`relaxed-caps` 这个插件

可以参考https://appiumpro.com/editions/123-migrating-to-appium-20-part-1-capability-prefixes
引入插件后应该可以跟1.xx的方式一样正常使用了

**Comment by lyfengcc** [comment]
> Appium mocker 这个工具只是mock出一个与Appium server交互的client，具体client的表现其实是依赖于Appium mocker中引用的appium-java-client的版本. 目前appium mocker中基于的appium-java-client版本是7.3.0。
> 
> 据我了解，appium2.0 对capabilities prefix做了一些更严格的约束，原有的appium client不一定能直接支持2.0的appium，你可以在appium2.0上试着引用`relaxed-caps` 这个插件
> 
> 可以参考https://appiumpro.com/editions/123-migrating-to-appium-20-part-1-capability-prefixes 引入插件后应该可以跟1.xx的方式一样正常使用了

好的，感谢🙏
